ProjectUnite/ProjectUnite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
	url(r'^$', 'profiles.views.home', name='home'),
    url(r'^myProjects/$', 'projects.views.my_projects', name='my_projects'),
	url(r'^contact/$', 'profiles.views.contact', name='contact'),
	url(r'^edit/$', 'profiles.views.edit_profile', name='edit_profile'),
	url(r'^projectlist/$', 'projects.views.projectlist', name='projectlist'),
    url(r'^newProject/$', 'projects.views.newProject', name='newProject'),
    url(r'^all/$', 'profiles.views.all', name='all'),
	#url(r'^about/$', 'ProjectUnite.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^projects/(?P<projectID>\w+)/$','projects.views.single_project', name = 'single_project'),
    url(r'^members/(?P<username>\w+)/$','profiles.views.single_user', name = 'single_user'),
    url(r'^accounts/', include('registration.backends.default.urls')),
] 
if settings.DEBUG:
	urlpatterns +=  static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ProjectUnite/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class SignUp(models.Model):
	#user = models.ForeignKey(SignUp)
	email = models.EmailField()
	user = models.ForeignKey(User)
		
	full_name = models.CharField(max_length=40)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
		#might need text widget
	skills = models.TextField()
		#Qualifications = models.TextField()
	Experience = models.TextField()
	CurrentDegree = models.CharField(max_length=40, blank = True, null = True)
	Currentprojects = models.TextField()
	location = models.CharField(max_length=40)
	active = models.BooleanField(default = True)

		
	def __unicode__(self):
		return self.email
# Create your models here.

#class SearchProfiles(models.Model):

class UserPicture(models.Model):
	user = models.ForeignKey(User)
	image = models.ImageField(upload_to='profiles/')
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	active = models.BooleanField(default = True)
	thumbnail = models.BooleanField(default = False)
	def __unicode__(self):
		return str(self.image)

ProjectUnite/templates/all.html
  {% extends "base.html" %}
  {% block content %}
  {% for user in users %}
  <li><a href = '/members/{{ user.username }}'>{{ user }}</a> {% for item in user.SignUp_set.all %}{{ item }}{% endfor %}</li>
  {% endfor %}
  {% endblock %}

ProjectUnite/templates/allproject.html
  {% extends "base.html" %}
  {% block content %}
  <h1> Search results for Projects </h1>


 {% for project in projects %}
  <li><a href = '/projects/{{ project.projectID }}'>{{ project }}</a> {% for item in project.ProjectTitle_set.all %}{{ item }}{% endfor %}</li>
  {% endfor %}

  <h4>Testing</h4>
  {% endblock %}

ProjectUnite/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Project Unite</title>
    <h1>Testing</h1>
    <!-- Bootstrap core CSS -->

    <link href="{ static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

   <link href=" {{ STATIC_ROOT }} " rel = "stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Static navbar -->
   {% include 'navbar.html' %}
   <div class = "body-content">
    <div class = 'row'>
    <div class = 'col-lg-2 col-12'>
      <ul class = 'nav nav-pills nav-stacked'>
        <li><a href = '/'><span class = 'badge pull-right'>8</span>Home</a></li>
        <li><a href = '/'>Myprojects</a></li>
    </div>
    <div class= 'col-lg-10 col-12'>
      {% block content %}

      {% endblock %}
    </div>
      <!-- Main component for a primary marketing message or call to action -->
    
    </div> <!-- /container -->
  </div>
     Latest compiled and minified CSS CDN
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

   <style>
    title {
  
  color: #d0e4fe;
}

  h1 {
    color: orange;

  }

  body {
    
    color: red;
  }

   </style>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

ProjectUnite/templates/error.html
{% extends "base.html" %}
{% block content %}
{{ title }}
{% endblock %}

ProjectUnite/templates/forms.html
<form method='POST' action = '.'>{% csrf_token %}
{{ form.as_p }}
<input type = 'submit' value = 'Submit'/>
</form>

ProjectUnite/templates/home.html
  {% extends "base.html" %}
  {% load crispy_forms_tags %}
  {% block content %}
  <div class="jumbotron">
        <h1>Welcome To Project Unite</h1>
        <p>Here at Project Unite we make finding group memebers easy. It could be a capstone project or a great iphone app we can help connect you with people that have the skills you need</p>
      
      </div>

{% endblock %}

ProjectUnite/templates/myProjects.html
 {% extends "base.html" %}
  {% block content %}
 <h1>Page under Construction</h1>
  {% endblock %}

ProjectUnite/templates/navbar.html
 <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Project Unite</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="/projectlist">Search Projects</a></li>
            <li><a href="/all">Search Users</a></li>
            <li><a href="/newProject">Create/Edit Project</a></li>
            {% else %}


            {% endif %}
     
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              
        
              <li><a>{{ request.user }}</a></li>
              <li><a href="/edit">Edit Profile</a></li>
              <li><a href="/myProjects">My Projects</a></li>
              <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            <li><a href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
          </ul>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav>

ProjectUnite/templates/newProject.html
 {% extends "base.html" %}
 {% load crispy_forms_tags %}
   {% block content %}
 <h1> Create/Edit a new project</h1>

<form method='POST' action = '.'>{% csrf_token %}
	{{ form|crispy }}
	
<input class = 'btn btn-primary' type='submit' value = 'SUBMIT'/>
</form>


  {% endblock %}

ProjectUnite/templates/single_project.html
 {% extends "base.html" %}
 {% load i18n %}
{% load crispy_forms_tags %}
 {% block content %}
 <h1>information for Project {{ single_project }}</h1>
 <ul>
 <li>Title: {{ single_project.title }}</li>
 <li>Location: {{ single_project.location }}</li>
 <li>Description: {{ single_project.description }}</li>
 <li>Team Members: {{ single_project.team_members }}</li>
 <li>Author: {{ single_project.user }}</li>
 <li>Contact Email: {{ single_project.contact_email }}</li>
</ul>



 {% endblock %}

ProjectUnite/templates/single_user.html
 {% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
 {% block content %}
 <h1>Profile for {{ single_user }}</h1>
<div class = 'row'>
<div class = 'col-lg-6'>

{% for item in single_user.userpicture_set.all %}
<li><img src = '{{ MEDIA_URL }}{{ item }}' height = "50" width "50"></li>

{% endfor %}
</div>
  <div class = 'col-lg-6'>
<div class = 'panel'
	<div class = 'panel-heading'> User Information</div>



 <ul>
 	{% for item in single_user.signup_set.all %}
	<li>Name: {{ item.full_name }}</li> 
	<li>Email: {{ item.email }}</li>
	<li>CurrentDegree: {{ item.CurrentDegree }}</li> 
	<li>location: {{ item.location }}</li> 
</ul>
</div>
<div class = 'col-lg-6'>
<div class = 'panel'>
	<div class = 'panel-heading'></div>
<ul>
	
</ul>
</div>
</div>
<div class = 'col-lg-6'>
<div class = 'panel'>
	<div class = 'panel-heading'>Skills and Experience</div>
<ul>
	<li>Skills:</br><p> {{ item.skills }}</li></p> 
	<li>Experience:</br><p> {{ item.Experience }}</li></p>
	<li>Currentprojects:</br> {{ item.Currentprojects }}</li> </p>
</ul>
</div>
</div>
	

	
	{% endfor %}
</ul>
</div>

 {% endblock %}

ProjectUnite/templates/update_profile.html
  {% extends "base.html" %}
  {% load crispy_forms_tags %}

  {% block content %}
<form method='POST' action = '.'>{% csrf_token %}
	{{ signup_form|crispy }}
	<div class = 'row'>
	{{ user_picture_form.as_p }}
	</div>
<input class = 'btn btn-primary' type='submit' value = 'UPDATE'/>
</form>


  {% endblock %}